version: 2.1

jobs:
  git-going:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: gitting deep
          command: |
            mkdir -p '/Users/distiller/project'
	          cd '/Users/distiller/project'
	          git clone --depth 1 -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL" .
	          git --no-pager log --no-color -n 1 --format='HEAD is now at %h %s'

workflows:
  git-down:
    jobs:
      - git-going
    
